replicaCount: 1

image:
  repository: frozenwater1/my-spring-kafka
  tag: 4ee64d8
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8082

kafka:
  bootstrapServers: kafka.default.svc.cluster.local:9092

resources: {}